import { GET_CATEGORIES_QUERY, GET_CATEGORY_DETAILS_QUERY } from "./categories";
import { GET_PRODUCTS_QUERY, GET_PRODUCT_DETAILS_QUERY } from "./products";

export {
  GET_CATEGORIES_QUERY,
  GET_CATEGORY_DETAILS_QUERY,
  GET_PRODUCTS_QUERY,
  GET_PRODUCT_DETAILS_QUERY,
};
